apiVersion: batch/v1
kind: Job
metadata:
  name: jira-issue-fetcher-manual
  labels:
    app: jira-issue-fetcher
    component: manual-job
  annotations:
    description: "Manual execution of Jira issue fetcher for testing"
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  activeDeadlineSeconds: 1800  # 30 minutes max runtime
  template:
    metadata:
      labels:
        app: jira-issue-fetcher
        component: manual-pod
    spec:
      restartPolicy: Never
      containers:
      - name: jira-issue-fetcher
        image: 'jira-issue-fetcher:prod'
        imagePullPolicy: Always
        env:
        - name: JIRA_URL
          valueFrom:
            secretKeyRef:
              key: JIRA_URL
              name: mcp-atlassian-secret
        - name: JIRA_TOKEN
          valueFrom:
            secretKeyRef:
              key: JIRA_PERSONAL_TOKEN
              name: mcp-atlassian-secret
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: REDIS_URL
              name: x-beeai-agent-configmap
        - name: QUERY
          valueFrom:
            configMapKeyRef:
              key: QUERY
              name: jira-issue-fetcher
        - name: LOGLEVEL
          value: "DEBUG"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30