apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-server-git-repos
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: crc-csi-hostpath-provisioner
  volumeMode: Filesystem
